language: python
python:
- '3.5'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- PYTHONPATH=.:djangoproject py.test -k "not djangoproject"
- PYTHONPATH=. py.test djangoproject

notifications:
  slack:
    - secure: LfKPIzFzqSWmK+ccNWzy005WXUFSDQ0iVGPUNgAerg0fSR8XTKpxaMkp0JtcHOIvD9wyNMZ43gItBiEBX2BVyB//4RO2PpLokBDYVtKV8N9LcCjlGPI/7JoglhmA2zBMuplAQO8QHQM50xd6vdDbvF+UxvlPyg8XX+/qGPmadYzQwjZL5iYIt214zXfQI613HmPFFjdzwY//v8sAe2MV8jjBO/0q3bS+DgSxE9HEzDOBZEsEyFOFgch2xBGqk2W6TvDnDewuktnMgfifC4pL93PyUjiFPm6aIWBJU6WgP6DoOWebXWzeRSsqufR3c8Nkzo7c1J91obNwCANhUPG4ZpkaASgyQve/eipWSeqaexGsxSLOfXcfPtpznfRerikFQ+dn5gTV1AEvslRZhBt2VPY6yJ38Z4k56+cxCU6mLyU9Dn0uKD7TWDUuYLQtesb6n8eayKdY29UiuXeHvHG1KdjCtW/wIJys8Qq3ey64CQd2EB2QmRtymWutvq2I87G0H9BFR2YYdjOc0U4Edmc09LaBodsdoU9mEHhcrr8O7xGaNrA1o9ih8yuD25Q0otmOZ123IOGHeiaLMuzD9MXRVNO/utbHRkiW28AFbDZHkgu6VIKkj5odw+wBrOAJx1Jyf163l9mXztc9AADZN4Bw04Y308jTf1/u+Nj0YsUc3yM=
    - secure: vmjhklCsw/RBhG2zfgY3w40pZWMKGJE49JJSBqVVEFQxnYZPfs+XobanLW7tgB3WSRc/NUFDpfj7NpegGLWXwWLgDlmFsgw+4+/9E1XqXmjjyPRVDti2cEwav0Z0SNjyQCZ6+9DvEpd8I+NsEOamlmh/6Ywy9NRT643SVLGPPW41Agoh8A7t8MdSDp2ix6xOdiEIseCoDs+Z3CDhndLuLZIleiNsgdxESt94fqJ2r9CdoTQ9v7hfTTmL0dcP4Q5FDqpX7Ion0OSKpp2VagbqUsmbqCszHspxAobkJV5yAoOsQd63yYegdOjM+RFiTMMqAKETjkTSmQQ+3niLzowoUZ5aAguqgKi6Wrtv7mjvvtH03kQa+uwoS6e7vATBG8OYs1y66OdaUMgyaBDDxFCbYpSivwcXQNQk9ENJk+hZrApMZLSYZIw+GlIBL8Da3KHu7/8kMNgjl+o98fkRKfJRXynOW7TZl/f5bDxpvSYU9uBGinMfE+vyYrBbFaNSKxl3rXBCyTZJglMp/0qig6loIfFH+JxXnQdz5Hz/eg1gOc0960spQp4E/OOAYvCPWOs30KLndmVLLWUgUzFWtU8ufPW7BK+YyJBqLJ1EHoVwS01u2MbF6O/EfyCoM7qfSsUAjxQR1Q1qKp6Y6a3KHxDTLqrJU7X4bbhvmxGHtlh8Vxg=
  email: false
